# Automatically generated by configure - do not modify
prefix=/usr/local
bindir=$(DESTDIR)/usr/local/bin
tccdir=$(DESTDIR)/usr/local/lib/tcc
libdir=$(DESTDIR)/usr/local/lib
includedir=$(DESTDIR)/usr/local/include
mandir=$(DESTDIR)/usr/local/share/man
infodir=$(DESTDIR)/usr/local/share/info
docdir=$(DESTDIR)/usr/local/share/doc
CC=/usr/local/bin/tcc
CC_NAME=tcc
GCC_MAJOR=0
GCC_MINOR=927
AR=/usr/local/bin/tcc -ar
CFLAGS=-Wall -O2
LDFLAGS=
LIBSUF=.a
EXESUF=
DLLSUF=.dylib
NATIVE_DEFINES+=-DCONFIG_USR_INCLUDE="\"/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include\""
ARCH=x86_64
TARGETOS=Darwin
CONFIG_OSX=yes
VERSION = 0.9.27
TOPSRC=$(TOP)
