# Automatically generated by configure - do not modify
prefix=/usr/local
bindir=$(DESTDIR)/usr/local/bin
tccdir=$(DESTDIR)/usr/local/lib/tcc
libdir=$(DESTDIR)/usr/local/lib
includedir=$(DESTDIR)/usr/local/include
mandir=$(DESTDIR)/usr/local/share/man
infodir=$(DESTDIR)/usr/local/share/info
docdir=$(DESTDIR)/usr/local/share/doc
CC=clang
CC_NAME=clang
GCC_MAJOR=13
GCC_MINOR=0
AR=ar
CFLAGS=-Wall -O2 -Wdeclaration-after-statement -fno-strict-aliasing -fheinous-gnu-extensions -Wno-pointer-sign -Wno-sign-compare -Wno-unused-result -Wno-string-plus-int
LDFLAGS=
LIBSUF=.a
EXESUF=
DLLSUF=.dylib
NATIVE_DEFINES+=-DCONFIG_USR_INCLUDE="\"/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include\""
ARCH=x86_64
TARGETOS=Darwin
CONFIG_OSX=yes
VERSION = 0.9.27
TOPSRC=$(TOP)
